-- ============================================================
-- SUNRISE DENTAL CLINIC
-- Appointment Database Verification Queries
-- ============================================================

USE sunrise_dental_db;


-- ------------------------------------------------------------
-- TEST 1: Check Appointment Table
-- ------------------------------------------------------------

SHOW CREATE TABLE appointments;


-- ------------------------------------------------------------
-- TEST 2: Inspect supporting entities
-- ------------------------------------------------------------

SHOW COLUMNS FROM patients;
SHOW COLUMNS FROM dentists;
SHOW COLUMNS FROM treatments;


-- ------------------------------------------------------------
-- TEST 3: Appointment Details View
-- ------------------------------------------------------------

SELECT *
FROM vw_appointment_details
ORDER BY appointment_date, appointment_time;


-- ------------------------------------------------------------
-- TEST 4: Stored Function
-- ------------------------------------------------------------

SELECT
    treatment_code,
    treatment_name,
    treatment_price,
    consultation_fee,
    fn_calculate_treatment_total(
        treatment_price,
        consultation_fee
    ) AS calculated_total
FROM treatments
ORDER BY treatment_id;


-- ------------------------------------------------------------
-- TEST 5: Daily Schedule Stored Procedure
-- ------------------------------------------------------------

CALL sp_get_daily_appointment_schedule('2026-09-01');


-- ------------------------------------------------------------
-- TEST 6: Memento Appointment History
-- ------------------------------------------------------------

SELECT
    history_id,
    appointment_id,
    appointment_number,
    patient_id,
    dentist_id,
    treatment_id,
    appointment_date,
    appointment_time,
    status,
    notes,
    changed_by,
    change_type,
    changed_at
FROM appointment_history
ORDER BY history_id;


-- ------------------------------------------------------------
-- TEST 7: Trigger Protection
-- IMPORTANT:
-- This query SHOULD FAIL with MySQL error #1644.
-- ------------------------------------------------------------

-- DELETE FROM appointments
-- WHERE appointment_id = 4;


-- ------------------------------------------------------------
-- TEST 8: Verify protected appointment remains
-- ------------------------------------------------------------

SELECT
    appointment_id,
    appointment_number,
    appointment_date,
    appointment_time,
    status
FROM appointments
WHERE appointment_id = 4;









/* ================================================================
   SUNRISE DENTAL CLINIC
   USER MANAGEMENT AND SECURITY AUDIT VERIFICATION
   ================================================================

   Purpose:
   These queries verify the database state used by the staff account
   management, authentication, role-based access control and security
   audit functionality.

   The queries are intentionally read-only so they can be executed
   safely without changing clinical or administrative data.
   ================================================================ */


/* ----------------------------------------------------------------
   TEST 1 — STAFF ACCOUNT SUMMARY
   Expected:
   - Every user has a unique username.
   - Role is ADMIN or RECEPTIONIST.
   - is_active is 0 or 1.
   ---------------------------------------------------------------- */

SELECT
    user_id,
    username,
    full_name,
    role,
    is_active,
    created_at
FROM users
ORDER BY user_id;


/* ----------------------------------------------------------------
   TEST 2 — VALID ROLE CONSTRAINT
   Expected result:
   invalid_role_count = 0
   ---------------------------------------------------------------- */

SELECT
    COUNT(*) AS invalid_role_count
FROM users
WHERE role NOT IN (
    'ADMIN',
    'RECEPTIONIST'
);


/* ----------------------------------------------------------------
   TEST 3 — DUPLICATE USERNAME CHECK
   Expected result:
   No rows returned.
   ---------------------------------------------------------------- */

SELECT
    username,
    COUNT(*) AS duplicate_count
FROM users
GROUP BY username
HAVING COUNT(*) > 1;


/* ----------------------------------------------------------------
   TEST 4 — ACTIVE ADMINISTRATOR SAFETY CHECK
   Expected:
   active_admin_count >= 1

   The application service also prevents the final active ADMIN
   account from being deactivated or demoted.
   ---------------------------------------------------------------- */

SELECT
    COUNT(*) AS active_admin_count
FROM users
WHERE role = 'ADMIN'
  AND is_active = 1;


/* ----------------------------------------------------------------
   TEST 5 — PASSWORD STORAGE FORMAT CHECK
   Expected:
   plaintext_or_invalid_password_count = 0

   Password hashes generated by the application use the format:
   iterations:salt:derivedHash

   Do not display the actual password_hash values in report evidence.
   ---------------------------------------------------------------- */

SELECT
    COUNT(*) AS plaintext_or_invalid_password_count
FROM users
WHERE password_hash IS NULL
   OR password_hash = ''
   OR password_hash NOT LIKE '%:%:%';


/* ----------------------------------------------------------------
   TEST 6 — SECURITY AUDIT LOG SUMMARY
   Expected:
   LOGIN_SUCCESS and/or LOGIN_FAILURE records after authentication
   tests have been performed.
   ---------------------------------------------------------------- */

SELECT
    action_type,
    COUNT(*) AS event_count
FROM audit_logs
GROUP BY action_type
ORDER BY action_type;


/* ----------------------------------------------------------------
   TEST 7 — RECENT SECURITY AUDIT EVENTS
   Expected:
   Recent login activity appears with timestamp and source IP.

   Sensitive information such as passwords and password hashes must
   never appear in the audit description.
   ---------------------------------------------------------------- */

SELECT
    audit_id,
    user_id,
    action_type,
    entity_type,
    entity_id,
    description,
    ip_address,
    created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT 20;


/* ----------------------------------------------------------------
   TEST 8 — AUDIT PASSWORD LEAK CHECK
   Expected result:
   suspicious_audit_record_count = 0
   ---------------------------------------------------------------- */

SELECT
    COUNT(*) AS suspicious_audit_record_count
FROM audit_logs
WHERE LOWER(COALESCE(description, ''))
          LIKE '%password%';


/* ----------------------------------------------------------------
   TEST 9 — ORPHANED AUDIT USER REFERENCES
   Expected result:
   orphaned_audit_user_count = 0

   LOGIN_FAILURE entries may intentionally contain NULL user_id
   because authentication may fail before a valid user is resolved.
   ---------------------------------------------------------------- */

SELECT
    COUNT(*) AS orphaned_audit_user_count
FROM audit_logs al
LEFT JOIN users u
    ON u.user_id = al.user_id
WHERE al.user_id IS NOT NULL
  AND u.user_id IS NULL;


/* ----------------------------------------------------------------
   TEST 10 — USER ACCOUNT STATUS SUMMARY
   Useful for validating activation/deactivation functionality.
   ---------------------------------------------------------------- */

SELECT
    role,
    is_active,
    COUNT(*) AS account_count
FROM users
GROUP BY
    role,
    is_active
ORDER BY
    role,
    is_active DESC;


/* ----------------------------------------------------------------
   TEST 11 — LOGIN AUDIT RELATIONSHIP
   Expected:
   Successful login events resolve to an existing staff account.
   Failed login events may have no user_id.
   ---------------------------------------------------------------- */

SELECT
    al.audit_id,
    al.action_type,
    al.user_id,
    u.username,
    u.role,
    al.ip_address,
    al.created_at
FROM audit_logs al
LEFT JOIN users u
    ON u.user_id = al.user_id
WHERE al.action_type IN (
    'LOGIN_SUCCESS',
    'LOGIN_FAILURE'
)
ORDER BY al.created_at DESC;


/* ================================================================
   END — USER MANAGEMENT AND SECURITY AUDIT VERIFICATION
   ================================================================ */